Add queue restart task
capistrano/laravel pull request #47
Opened 2018-05-31 17:57 UTC by luizguilhermefr

As in [docs](https://laravel.com/docs/5.6/queues#queue-workers-and-deployment), you should restart the queue workers after every deploy.

Added this functionality, successfully tested on my company's production environment.

2021-03-02 01:59 UTC, ikari7789 requested changes

2021-03-02 01:59 UTC, ikari7789 commented on README.md
> +after 'composer:run',     'laravel:restart_queue'
Please align 'composer:run' with the other lines.

```
after  'composer:run',    'laravel:storage_link'
after  'composer:run',    'laravel:optimize'
after  'composer:run',    'laravel:optimize'
after  'composer:run',    'laravel:restart_queue'
```

2021-03-02 01:59 UTC, ikari7789 commented on lib/capistrano/tasks/laravel.rake
> +	end
Please indent this block.

2021-03-02 02:00 UTC, ikari7789 commented on lib/capistrano/tasks/laravel.rake
> +
Please remove extra newline.

2021-05-27 10:29 UTC, lastthyme approved these changes

2022-06-21 15:47 UTC, closed without merging